### PR TITLE
Not returning if register node get error

### PR DESCRIPTION
**Pull request by gutorc92**
Signed-off-by: Gustavo Coelho <gutorc@hotmail.com>

solves #2

### CODE REVIEW

**Review by flaviostutz — CHANGES_REQUESTED** [review]
What do you think about those changes?

**Comment by gutorc92** [comment]
> What do you think about those changes?

@flaviostutz, the message on line 61 could be change to "Registration on ETCD done." because it will be printed when the registration process is done right.

**Comment by flaviostutz** [comment]
@gutorc92 are the proposed changes OK for you?

**Comment by gutorc92** [comment]
> @gutorc92 are the proposed changes OK for you?

Yes

**Review by gutorc92 — COMMENTED** [review]
Could you change line 61 message to "Registration on ETCD done."?

**Comment by flaviostutz** [comment]
Great! Thanks!

**Pull request merged**
